### ISSUE TITLE
Binaries should be tracked by Git LFS

### ISSUE THREAD

**Issue by kirb** [ParasiteTeam/installer#1]
Was going to send a PR but apparently Git LFS objects can’t currently be added to a GitHub fork…

In its current state, cloning this repo means having to download the entire history of binaries. LFS is stored separate from the repo, on a CDN, and cloning the repo means only downloading the latest versions of the binaries.

``` shellsession
git lfs track Parasite.kext/Contents/MacOS/Parasite \
  Parasite.kext/Contents/Resources/ParasiteLoader.dylib \
  ParasiteRuntime.framework/Versions/A/ParasiteRuntime \
  ParasiteRuntime.framework/Versions/A/Resources/libsubstitute.dylib
```

**Comment by shinvou** [comment]
We'll use releases. Closed. :)
