### ISSUE TITLE
Hopper Crash 

### ISSUE THREAD

**Issue by iMokhles** [ParasiteTeam/installer#2]
i installed it ( everything goes well till i opened Hopper )

it crashes ( talked with Hopper author ) he told me that Hopper protect itself from such tools 

so do you plan to add Hopper support ( or just flag it once we add ( any mode in the plist file ) ?

crash log " http://pastebin.com/qcRTzuUG "

thanks

**Comment by shinvou** [comment]
Blacklisted Hopper in kext.
