### ISSUE TITLE
Installer does not give out any options - rather skips to a #?

### ISSUE THREAD

**Issue by ghost** [ParasiteTeam/installer#4]
The new installer script does not allow for any user actions upon running in Terminal with El Capitan.

The choices appear but as output a "#?" is given and upon a second run it outputs the same as a
result there's not much to do. The scripts exits promptly.  Parasite does not get installed. Two folders are made; a parasite one in private/tmp and one in /library/

Can you please update the script so that updating+uninstalling+installing parasite becomes options.

**Comment by alexzielenski** [comment]
For now, instead of curling it and running directly off of GitHub, try downloading the `sh` file to your local disk, run "chmod +x ~/path/to/install.sh" and then run it as sudo

**Comment by ghost** [comment]
That works. Thanks!

**Comment by justin0a0** [comment]
I'll check tonight after work and see why it does that and see what i can do to make it a bit easier to use.

**Comment by justin0a0** [comment]
I have come to the conclusion that this script does not like to work properly when piped so I changed the install command now its two lines but it's still an easy process.
