### ISSUE TITLE
Parasite Installer reboots Mac

### ISSUE THREAD

**Issue by ghost** [ParasiteTeam/installer#7]
Lately, I tried installing Parasite on to my macOS Sierra installation. But, the Parasite installer does not install anything - rather it just reboots the entire computer with no question asked. 

It tries to apply the .kext it would appear. I have SIP disabled across the board. And also allowed the extra choice to install from Anywhere rather than just the 2 options within a regular Sierra installation.

Help?!

**Comment by justin0a0** [comment]
See here: https://github.com/ParasiteTeam/kext/issues/3
