### ISSUE TITLE
Running installer causes kernel panic

### ISSUE THREAD

**Issue by NSExceptional** [ParasiteTeam/installer#8]
macOS 10.12.3 build 16D32
MacBookPro13,3 (2017)

**Comment by justin0a0** [comment]
This wasn't never intended for 10.12.X
Most likely will never be updated to support it.
There was no community effort towards any of it and interest was lost.

**Comment by NSExceptional** [comment]
Leave the issue open then and assign it to me.

**Comment by justin0a0** [comment]
The issue isn't the installer it's with the Kext. If you want to get into that be our guest!

**Comment by NSExceptional** [comment]
Good to know! Anything else I should be aware of that might help?

**Comment by justin0a0** [comment]
Not really it should honestly be stable enough again if some time was spent but I gave up long ago cuz I couldn't get any type of debugging to work and figure out what kills the kernel.

**Comment by shinvou** [comment]
I actually have a working version on 10.12. If you have any questions, feel free to ask.

**Comment by alexzielenski** [comment]
Where is it lol

**Comment by shinvou** [comment]
On my hard drive, haha. Dunno if I should release since it's very hacky.

**Comment by alexzielenski** [comment]
Isn't everything abou this project hacky?

**Comment by NSExceptional** [comment]
Yeah... if it works, release it! Push it to master!

(At the very least, push it to a separate branch)

**Comment by NSExceptional** [comment]
Bump @shinvou

**Comment by NSExceptional** [comment]
Is the Kernel Debug Kit from Apple not helpful for this?

> [The Kernel Debug Kit] contains development and debug versions of the OS X kernel and many I/O Kit families for use with LLDB remote (two-machine) kernel debugging. These files contain full symbolic information, unlike the equivalent files in a normal OS X installation. Also included are LLDB macros useful for kernel debugging and DEVELOPMENT (for everyday use) and DEBUG (for much more error checking) kernels built with more assertions and fewer compiler optimizations.
